// AUTO-GENERATED FILE. DO NOT MODIFY. GENERATED BY
// scripts/generate_can_wrapper.py

#include "uwrt_mars_rover_can_wrapper.h"

using namespace HWBRIDGE;

// --- Message packer function prototypes ---

// -- Message unpacker function prototypes ---

bool HWBRIDGE::packCANMsg(uint8_t *raw, CANID msgID, const CANMsgMap *msgMap,
                          size_t &len) {
  switch (msgID) {

  default:
    return false;
  }
}

bool HWBRIDGE::unpackCANMsg(uint8_t *raw, CANID msgID, CANMsgMap *msgMap) {
  switch (msgID) {

  default:
    return false;
  }
}
